spring:
  application:
    name: voting
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:secret}
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
      channel-name: voting-channel


  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  shutdown: immediate
